version: "3.7"

services:
  client:
    build: ./client
    ports:
      - "1234:1234"
      - "1235:1235"
    volumes:
      - ./client/src:/usr/src/client/src
    depends_on:
      - server
  
  server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server/src:/usr/src/server/src
    depends_on:
      - database

  database:
    image: 'mongo'
    container_name: 'mongo-container'
    environment:
      # - MONGO_INITDB_DATABASE=blog-system
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    # volumes:
    #   # - ./init-mongo.js:/docker-entrypoint-initdb.d/initmongo.js:ro
    #   - blog-data ./mongo-data:/data/db
    ports:
      - '27017-27019:27017-27019'

# volumes:
#   blog-data:
